

export const searchResultFakeData = [
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    isLiked: false,
    owner: "John Doe",
    creator: "John Doe",
    id: 0,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 1,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 2,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 3,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    isLiked: false,
    id: 4,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 5,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 6,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 7,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 8,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 9,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 10,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 11,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 12,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 13,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 14,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 15,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 16,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 17,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 18,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    isLiked: false,
    creator: "John Doe",
    id: 19,
  },
  {
    imageUrl: "",
    price: 2.59,
    isLiked: false,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 20,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 21,
    isLiked: false,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 22,
    isLiked: false,
  },
  {
    imageUrl: "",
    isLiked: false,
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    id: 23,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    isLiked: false,
    id: 24,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    isLiked: false,
    id: 25,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    isLiked: false,
    creator: "John Doe",
    id: 26,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    isLiked: false,
    creator: "John Doe",
    id: 27,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    isLiked: false,
    id: 28,
  },
  {
    imageUrl: "",
    price: 2.59,
    likesCount: 1,
    owner: "John Doe",
    creator: "John Doe",
    isLiked: false,
    id: 29,
  },
];
